language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='scipy numpy coveralls coverage h5py mock requests six appdirs python-geotiepoints dask'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
matrix:
  include:
    - env: PYTHON_VERSION=2.7
      os: linux
    - env: PYTHON_VERSION=2.7
      os: osx
      language: generic
    - env: PYTHON_VERSION=3.6
      os: linux
    - env: PYTHON_VERSION=3.6
      os: osx
      language: generic
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
script: coverage run --source=pyspectral setup.py test
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; fi
deploy:
  - provider: pypi
    user: adybbroe
    password:
      secure: SY0qo7sZXDjDx0DHvuXrHvL9VTAulgU/T33d6UWXf469jT9DOexuZ2VYLgJbYQen5FSe5JmQE0ZMdId1cb8IPP/77qCgQK6f0lRDa43fSYXhcD+fHzlQskievJrwamkRYx6WBrJbwGAKBNinUgNSaTdbh9XUugziGFiOHUfVppM=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
      repo: pytroll/pyspectral
notifications:
  slack: pytroll:LR63XVq1cT8kVc3fnXKIZmYr
