language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
# command to run tests, e.g. python setup.py test
#script:  python setup.py test
script: coverage run --source=pyspectral setup.py test
